const DIVIDER_LINE = '#F0F1F7'
const BUTTON_BACKGROUND = '#6209D9'
const BUTTON_TITLE = '#FFFFFF'
const SCREEN_BACKGROUND = '#FFFFFF'
const TAB_BAR = '#FFFFFF'
const TAB_BAR_ICON_ACTIVE = '#6209D9'
const TAB_BAR_ICON_DEFAULT = '#0E0E16'
const TEXT_ACCENT = '#6209D9'
const TEXT_DEFAULT = '#0E0E16'
const TEXT_LIGHT = '#848694'
const TEXT_SECOND = '#50515E'

const COLORS = {
    DIVIDER_LINE,
    BUTTON_BACKGROUND,
    BUTTON_TITLE,
    SCREEN_BACKGROUND,
    TAB_BAR,
    TAB_BAR_ICON_ACTIVE,
    TAB_BAR_ICON_DEFAULT,
    TEXT_ACCENT,
    TEXT_DEFAULT,
    TEXT_LIGHT,
    TEXT_SECOND,
}

export default COLORS
